name: Build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Download build from upstream
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run download
          cat setenv.txt >> $GITHUB_ENV
      - name: Generate hashsums
        run: sha256sum "freetube.pacman.tar.xz" > "freetube.pacman.tar.xz.sha256sum"
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./freetube.pacman.tar.xz*
          retention-days: 1
